baseURL = 'https://lflamonega.github.io/'
locale = 'es-ar'
title = 'Laureano F. Lamonega'
theme = 'no-style-please'

[params]
  description = 'Rompo cosas hasta que las saco andando. Hardware, Linux, infra y DevOps.'
  [params.theme_config]
    back_home_text = '← atrás'
