baseURL  = "https://lflamonega.github.io/"
locale   = "es-ar"
title    = "Laureano F. Lamonega"
copyright = "© Laureano F. Lamonega"

enableRobotsTXT = true

[params]
  description = "Laureano Francisco Lamonega."
