baseURL = 'https://lflamonega.github.io/'
locale = 'es-ar'
title = 'Laureano F. Lamonega'
theme = 'no-style-please'

[params]
  description = 'Sitio personal de Laureano Francisco Lamonega.'
  [params.theme_config]
    back_home_text = '← atrás'
